# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fast"
# The chunk rebuild scheduler mode (immediate, culling).
chunk_rebuild_scheduler = "culling"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enables dynamic lighting of beacon or end gateway beams.
	beam = true
	# Enables dynamic lighting of firefly particles from Firefly Bushes.
	firefly = true
	# Enables dynamic lighting for entities that have the Glowing effect.
	glowing_effect = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Enables dynamic lighting of the Warden's sonic boom attack particles.
	sonic_boom = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# Enables dynamic lighting of Guardian's lasers. This also can be toggled off by disabling Guardian dynamic lighting.
	guardian_laser = true

			[light_sources.settings.entities.minecraft]
				zombie_horse = true
				axolotl = true
				egg = true
				zoglin = true
				spawner_minecart = true
				allay = true
				llama = true
				mule = true
				bat = true
				husk = true
				camel = true
				experience_bottle = true
				rabbit = true
				firework_rocket = true
				silverfish = true
				giant = true
				drowned = true
				item = true
				goat = true
				horse = true
				vindicator = true
				minecart = true
				spectral_arrow = true
				llama_spit = true
				mooshroom = true
				glow_item_frame = false
				tnt = true
				snowball = true
				parrot = true
				creeper = true
				lightning_bolt = true
				tadpole = true
				ravager = true
				evoker_fangs = true
				chest_minecart = true
				tropical_fish = true
				slime = true
				pillager = true
				area_effect_cloud = true
				blaze = true
				piglin = true
				end_crystal = true
				endermite = true
				ender_pearl = true
				zombie = true
				item_display = true
				breeze_wind_charge = true
				guardian = true
				fireball = true
				illusioner = true
				eye_of_ender = true
				wither_skull = true
				wolf = true
				block_display = true
				tnt_minecart = true
				zombie_villager = true
				elder_guardian = true
				chest_boat = true
				boat = true
				small_fireball = true
				strider = true
				cave_spider = true
				cod = true
				snow_golem = true
				witch = true
				spider = true
				command_block_minecart = true
				panda = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				frog = true
				hoglin = true
				armadillo = true
				armor_stand = true
				experience_orb = true
				dolphin = true
				stray = true
				shulker = true
				turtle = true
				salmon = true
				vex = true
				wandering_trader = true
				wither_skeleton = true
				piglin_brute = true
				breeze = true
				ocelot = true
				furnace_minecart = true
				item_frame = true
				phantom = true
				ender_dragon = true
				leash_knot = true
				evoker = true
				marker = true
				glow_squid = true
				warden = true
				shulker_bullet = true
				squid = true
				enderman = true
				dragon_fireball = true
				chicken = true
				sniffer = true
				trader_llama = true
				donkey = true
				bogged = true
				fox = true
				iron_golem = true
				zombified_piglin = true
				cat = true
				wind_charge = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				villager = true
				ominous_item_spawner = true
				skeleton_horse = true
				fishing_bobber = true
				text_display = true
				polar_bear = true
				hopper_minecart = true
				falling_block = true
				painting = true
				interaction = true
				wither = true

			[light_sources.settings.entities.farmersdelight]
				rotten_tomato = true

			[light_sources.settings.entities.waves]
				waves = true

			[light_sources.settings.entities.crittersandcompanions]
				snail = true
				jumping_spider = true
				shima_enaga = true
				mud_ball = true
				roly_poly = true
				ladybug = true
				weevil = true
				otter = true
				dragonfly = true
				stick_bug = true
				leaf_insect = true
				stag_beetle = true
				koi_fish = true
				dumbo_octopus = true
				grappling_hook = true
				ferret = true
				red_panda = true
				sea_bunny = true

			[light_sources.settings.entities.powergrid]
				cord = true
				block_wire = true
				string_light_cord = true
				hanging_wire = true
				zap_projectile = true

			[light_sources.settings.entities.createnuclear]
				irradiated_wolf = true
				irradiated_cat = true
				irradiated_chicken = true

			[light_sources.settings.entities.tempad]
				timedoor = true

			[light_sources.settings.entities.vinery]
				mule = true
				dark_cherry_boat = true
				chair = true
				dark_cherry_chest_boat = true
				wandering_winemaker = true

			[light_sources.settings.entities.alexsmobs]
				devils_hole_pupfish = true
				kangaroo = true
				blue_jay = true
				skelewag = true
				bone_serpent_part = true
				catfish = true
				fart = true
				tasmanian_devil = true
				centipede_tail = true
				cosmic_cod = true
				rhinoceros = true
				comb_jelly = true
				jerboa = true
				mungus = true
				vine_lasso = true
				skunk = true
				bunfungus = true
				dropbear = true
				rattlesnake = true
				blobfish = true
				mimicube = true
				snow_leopard = true
				moose = true
				tiger = true
				rocky_roller = true
				rain_frog = true
				cosmaw = true
				mosquito_spit = true
				stradpole = true
				spectre = true
				hemolymph = true
				anaconda = true
				hammerhead_shark = true
				sunbird = true
				triops = true
				gazelle = true
				sea_bear = true
				tarantula_hawk = true
				void_worm_part = true
				void_worm_shot = true
				enderiophage = true
				void_portal = true
				terrapin = true
				platypus = true
				murmur = true
				void_worm = true
				bald_eagle = true
				centipede_body = true
				froststalker = true
				fly = true
				toucan = true
				cachalot_whale = true
				skreecher = true
				tossed_item = true
				bison = true
				pollen_ball = true
				mudskipper = true
				mud_ball = true
				gelada_monkey = true
				murmur_head = true
				cachalot_echo = true
				anteater = true
				laviathan = true
				enderiophage_rocket = true
				endergrade = true
				roadrunner = true
				cockroach_egg = true
				leafcutter_ant = true
				shoebill = true
				lobster = true
				grizzly_bear = true
				squid_grapple = true
				farseer = true
				potoo = true
				centipede_head = true
				flutter = true
				orca = true
				tendon_segment = true
				ice_shard = true
				maned_wolf = true
				crow = true
				banana_slug = true
				elephant = true
				crocodile = true
				crimson_mosquito = true
				sand_shot = true
				seal = true
				straddler = true
				emu = true
				mimic_octopus = true
				soul_vulture = true
				warped_mosco = true
				guster = true
				caiman = true
				tusklin = true
				underminer = true
				anaconda_part = true
				emu_egg = true
				gorilla = true
				flying_fish = true
				capuchin_monkey = true
				cockroach = true
				komodo_dragon = true
				bone_serpent = true
				mantis_shrimp = true
				seagull = true
				raccoon = true
				alligator_snapping_turtle = true
				giant_squid = true
				hummingbird = true
				straddleboard = true
				frilled_shark = true
				warped_toad = true
				shark_tooth_arrow = true
				gust = true
				sugar_glider = true

			[light_sources.settings.entities.sophisticatedbackpacks]
				everlasting_backpack_item = true

			[light_sources.settings.entities.mcwfurnitures]
				chair = true
				couch = true

			[light_sources.settings.entities.aether]
				slider = true
				poison_dart = true
				sun_spirit = true
				zephyr = true
				flying_cow = true
				whirlwind = true
				golden_dart = true
				poison_needle = true
				floating_block = true
				skyroot_boat = true
				mimic = true
				thunder_crystal = true
				sentry = true
				valkyrie_queen = true
				zephyr_snowball = true
				cockatrice = true
				hammer_projectile = true
				golden_swet = true
				skyroot_chest_boat = true
				fire_crystal = true
				fire_minion = true
				evil_whirlwind = true
				golden_parachute = true
				blue_swet = true
				cloud_minion = true
				valkyrie = true
				phyg = true
				aerbunny = true
				lightning_knife = true
				aerwhale = true
				cold_parachute = true
				enchanted_dart = true
				ice_crystal = true
				sheepuff = true
				aechor_plant = true
				moa = true
				cloud_crystal = true
				tnt_present = true

			[light_sources.settings.entities.railways]
				conductor = true
				benchcart = true
				jukeboxcart = true

			[light_sources.settings.entities.naturalist]
				deer = true
				alligator = true
				snail = true
				rhino = true
				bluejay = true
				snake = true
				catfish = true
				boar = true
				caterpillar = true
				dragonfly = true
				robin = true
				duck_egg = true
				tortoise = true
				butterfly = true
				duck = true
				bear = true
				sparrow = true
				lizard = true
				rattlesnake = true
				zebra = true
				canary = true
				firefly = true
				hippo = true
				coral_snake = true
				cardinal = true
				lion = true
				vulture = true
				bass = true
				giraffe = true
				lizard_tail = true
				elephant = true
				finch = true

			[light_sources.settings.entities.spawn]
				booby = true
				melon_seed = true
				tuna_egg = true
				barb = true
				snail = true
				tuna = true
				octopus = true
				spider_crab = true
				bluefish = true
				seal = true
				barbed = true
				crab_bubble = true
				sea_cow = true
				iguana = true
				herring = true
				pilot_fish = true
				angler_fish = true
				seahorse = true
				blenny = true
				frozen_crab_bubble = true
				ant = true
				hamster = true
				barracuda = true
				bird_egg = true
				stickbug = true
				coastal_crab = true
				stranded = true
				chest_boat = true
				firekeeper = true
				boat = true
				sneezed_salt = true
				sunfish = true
				marine_iguana = true
				flukeshroom = true
				dodo = true
				clam = true

			[light_sources.settings.entities.smallships]
				ground_cannon = true
				galley = true
				brigg = true
				drakkar = true
				cog = true
				cannon_ball = true

			[light_sources.settings.entities.immersive_aircraft]
				airship = true
				bamboo_hopper = true
				cargo_airship = true
				warship = true
				gyrodyne = true
				quadrocopter = true
				biplane = true
				tiny_tnt = true
				bullet = true

			[light_sources.settings.entities.ecologics]
				squirrel = true
				chest_boat = true
				boat = true
				penguin = true
				coconut_crab = true

			[light_sources.settings.entities.create]
				carriage_contraption = true
				seat = true
				stationary_contraption = true
				package = true
				contraption = true
				gantry_contraption = true
				super_glue = true
				crafting_blueprint = true
				potato_projectile = true

			[light_sources.settings.entities.tfmg]
				green_spark = true
				copper_grenade = true
				thermite_grenade = true
				spark = true
				dry_ice_flake = true
				napalm_bomb_entity = true
				blue_spark = true
				pipe_bomb = true
				zinc_grenade = true
				lithium_spark = true
				napalm_potato = true

			[light_sources.settings.entities.friendsandfoes]
				copper_golem = true
				glare = true
				illusioner = true
				player_illusion = true
				ice_chunk = true
				moobloom = true
				tuff_golem = true
				mauler = true
				iceologer = true
				wildfire = true
				crab = true
				rascal = true

			[light_sources.settings.entities.artifacts]
				mimic = true

			[light_sources.settings.entities.natures_spirit]
				ns_chest_boat = true
				ns_boat = true
				cheese_arrow = true

[debug]
	active_dynamic_lighting_cells = false
	display_dynamic_lighting_chunk_rebuild = false
	display_behavior_bounding_box = false

[adaptive_ticking]
	# Reduces how often sources behind the camera get ticked.
	background_sleep = true
	# How far away (in chunks) until light sources get ticked less often.
	slow = 5
	# How far away (in chunks) until light sources get ticked even less often.
	slower = 8
