#Config for Villager In A Bucket
#'enable-zombie-villager' should the ability to pick up Zombie Villagers in buckets be enabled. Default true
#
#Thu Jul 23 17:23:29 CEST 2026
enable-zombie-villager=true
